### PR TITLE
Multi formats extension

### PR DESCRIPTION
**Pull request by mcanouil**
This PR brings a Lua filter allowing to define the "titlepage" through yaml metadata, using `titlepage: great-wave`.

Most of the themes seem to work properly, except `great-wave` where the background image does not appear.
Probably some LaTeX fixing/tweaking.

Also, there is probably some part of the current templates which should rely on new metadata to avoid having to tweak the partials tex files.

I'll make some adjustment a bit later.

### CODE REVIEW

**Comment by eeholmes** [comment]
> This PR brings a Lua filter allowing to define the "titlepage" through yaml metadata, using `titlepage: great-wave`.
> 
> Most of the themes seem to work properly, except `great-wave` where the background image does not appear.
> Probably some LaTeX fixing/tweaking.
> 
> Also, there is probably some part of the current templates which should rely on new metadata to avoid having to tweak the partials tex files.
> 
> I'll make some adjustment a bit later.
> 

Nice! I can't the files as I  on very spotty internet on my phone. Re great-wave bg image: 

Does it need to be included as an asset in the _extension.yml?

Or perhaps something with the latex package being used?

**Comment by mcanouil** [comment]
I think the issue is on LaTeX side since `bg-image` has its image.
It's also possible I made a mistake while testing/refactoring the templates to make them work with the Lua filter.

**Comment by eeholmes** [comment]
@mcanouil Thanks for your work on the lua filter and before-body.tex template! I merged the changes and clean up a few things. The issue with great-wave was just that the default document class is scrartcl and I only was calling the cover for book document classes. I changed that so it shows up for non-book document classes too.

I am going to push over to the main branch, but first I need to update the documentation. For now it can be installed with

```bash
quarto install extension nmfs-opensci/quarto-titlepages@extension
```

**Comment by mcanouil** [comment]
You are welcome!
When you think it's ready, i.e., it follows your standards and everything seems to work as you expect, don't hesitate to ping me on https://github.com/mcanouil/awesome-quarto/issues/37 for me to add it to Awesome Quarto list. 😉

**Pull request merged**
